### PR TITLE
Adding new 1.16 blocks + brewing stands to chunk limits.

### PR DESCRIPTION
**Pull request by Convoy20**
Adding new 1.16 blocks + brewing stands to chunk limits.
If you do not merge this I will make blast furnace land. This is not a threat, it is a promise.

### CODE REVIEW

**Comment by Ameliorate** [comment]
Campfires might be a slight issue. Extinguished campfires make quite the nice building block.

**Comment by Convoy20** [comment]
> Campfires might be a slight issue. Extinguished campfires make quite the nice building block.

I'm dubious if this should be kept because of how campfire's models are multiblock I think they're way laggier than signs. Could bump the limit though.

**Comment by Convoy20** [comment]
Maybe we should include armor stands into this too?

**Comment by wingzero54** [comment]
> 
> 
> Maybe we should include armor stands into this too?

Would that conflict with the gui's which use invisible armor stands?

**Comment by wingzero54** [comment]
Also campfires ticked 692,813 times but only used 0.04% of the server, so I think we can safely leave them at 40

**Comment by Convoy20** [comment]
> > Maybe we should include armor stands into this too?
> 
> Would that conflict with the gui's which use invisible armor stands?

No, it should only be cancelling player interactions

**Comment by Diet-Cola** [comment]
Blocking armour stands probably wont work since theyre fully an entity, not a TileEntity

**Comment by Diet-Cola** [comment]
Plus it is way too easy to work around a chunk limit for armour stands

**Comment by Convoy20** [comment]
> Blocking armour stands probably wont work since theyre fully an entity, not a TileEntity

Can you check, don't know what it does to stop them from being placed.

**Comment by wingzero54** [comment]
Tested and confirmed the armor stand limit does nothing. This hack is a limit on block placement, but the armor stand becomes an entity when placed. I don't think the limit would ever come into play

**Comment by Convoy20** [comment]
> Tested and confirmed the armor stand limit does nothing. This hack is a limit on block placement, but the armor stand becomes an entity when placed. I don't think the limit would ever come into play

Removed armor stands from the config - should be good to go now

**Pull request merged**
