### PR TITLE
A smaller nerf to the Grinding Mill

### PR DESCRIPTION
**Pull request by Lodish**
it was 

32 stone -> 32 cobble
32 cobble -> 32 gravel
32 gravel -> 32 sand

and is changed to 

32 stone + 1 flint -> 32 cobble
32 cobble + 2 flint -> 24 gravel
32 gravel + 2 flint -> 24 sand

and the factory creation needs 64 flint, the repair 16 flint

### CODE REVIEW

**Comment by Protonull** [comment]
Doubt this will mollify the mob

**Comment by Convoy20** [comment]
> Doubt this will mollify the mob

*sharpens pitchfork*

**Comment by Virizion** [comment]
what's the point of this nerf

**Comment by Lodish** [comment]
> what's the point of this nerf

to reduce or make harder sand botting

**Comment by yodabird19** [comment]
Just...stop, please. I don't want arguing over the grinding mill to become my civ side job. 
We've been over this and over this now, there are better ways to nerf sand bots than to _nerf sand_.

**Comment by Protonull** [comment]
> Just stop and accept my opinion as fact

**Comment by wingzero54** [comment]
Not needed anymore

**Pull request closed without merging**
