### PR TITLE
obliterate the dreaded "t" shutdown message.

### PR DESCRIPTION
**Pull request by KaloHG**

### CODE REVIEW

**Comment by Convoy20** [comment]
This is an affront against old friend tradition

**Comment by TheOrangeWizard** [comment]
t

**Comment by AllenY** [comment]
t

**Comment by Quinndolin** [comment]
bump, any reasons against this?

**Comment by Convoy20** [comment]
> bump, any reasons against this?

tradition, common sense, possessing a shred of morality

**Comment by AllenY** [comment]
civclassics server is a t girl

**Comment by yodabird19** [comment]
t

**Pull request merged**
