### PR TITLE
Delete Old Banstick

### PR DESCRIPTION
**Pull request by Diet-Cola**

### CODE REVIEW

**Comment by Diet-Cola** [comment]
There are two bansticks in the plugins directory

**Comment by Protonull** [comment]
And two KiraBukkitRelays

**Comment by Diet-Cola** [comment]
Ahh so do we delete 1.2.1 which was uploaded 4 months ago or 1.2.0 which was 21 days ago 🤔

**Comment by wingzero54** [comment]
The newer one is correct, it has the cmc update. The older one is just from the 1.16 update, and Max marked the version as 1.2.0 so not sure why the jar was 1.2.1

**Pull request closed without merging**
