### PR TITLE
Config for CraftEnhance

### PR DESCRIPTION
**Pull request by Protonull**
Preliminary config for UnblockingHack, a hack which allows configs for additional crafting recipes for blocks combinations and un-combinations. Hopefully this PR serves as a forum for which blocks should be able to be combined and un-combined. One particularly glaring issue may be being able to craft Blocks of Quartz back into Quartz.

Something to keep in mind with the formatting is that the key is the ingredient and the value is the result. So for example `QUARTZ_BLOCK: QUARTZ` means that `QUARTZ_BLOCK` is the ingredient and `QUARTZ` is the result.

### CODE REVIEW

**Comment by TheOrangeWizard** [comment]
quartz block -> quartz recipe will crash the price of andesite/diorite/granite which are traded in some quantity. dunno if this is a bad thing considering they're just aesthetic blocks

sticks -> planks overlaps with and is more efficient than the existing sticks -> chests carpentry recipe. could be used to freely convert any wood -> oak but oak is the presumed default wood type anyway so probably not an issue

nether wart block -> nether wart was discussed in discord, one objection was that the blocks grown on nether trees could bypass rb times for xp production. this is not an issue imo as the fungus are fairly difficult to obtain and the trees are also high effort to harvest

no other complaints config wise, mostly seems like nice conveniences.

main query would be the reason for having this in SAH instead of a more mainstream crafting customising plugin

**Comment by Protonull** [comment]
Yeah, the Quartz conversion is what I'm most weary of given how you can create Blocks of Quartz in the Aesthetics Factory extremely cheaply (never been a fan of that tbh)

**Comment by Protonull** [comment]
Also, the `sticks -> oak planks` crafting recipe is not more efficient than the `sticks -> chests` factory recipe. Think about it, the vanilla `planks -> sticks` crafting recipe is 1:2 respectively, that for every 1 plank you put in you get 2 sticks out, which is why the your factory recipe results in 4 chests, because the 64 sticks covert into 32 planks worth of chests.

But with the `sticks -> oak planks` crafting recipe, the ratio is 4:1, that for every 4 sticks you put in you get 1 plank out. It is true that people could easily convert any wood type into oak, but doing so would halve their wood stocks.

**Comment by Protonull** [comment]
> main query would be the reason for having this in SAH instead of a more mainstream crafting customising plugin

So Wing also mentioned that almost immediately after I mentioned these changes in VC last night. I've never really looked into this before but if this is people's first reaction then I have to assume there's some pretty good custom recipe plugins out there. Do you have any recommendations?

And lastly, while it's true what you said about Netherwart Blocks, couldn't the same thing be said about the naturally spawning large red/brown mushrooms in roofed forest biomes? (As an aside, we might want to add those large mushrooms into Realistic Biomes if they aren't already)

**Comment by wingzero54** [comment]
https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-14-1-16-x-free.55883/ This is the one I think was recommended to me, you can use a GUI in-game to edit, add, remove crafting recipes and recipes based on whatever other blocks (stone cutter, etc)

**Comment by Protonull** [comment]
Just played around a little with it and the concerns that I raised last night are ever present here:

- CustomCrafting appears to be closed source, so updating it or integrating it with other civ plugins should we so choose would be difficult or at the very least extremely tedious.
- It has a dependency: WolfyUtilities. This isn't necessarily a bad thing in of itself but it's another thing we'll have to keep and eye on and update.
- It does a little bit more than add custom recipes, it also adds various custom crafting methods like an advanced workbench. We'd have to go through and disable any custom functionality like that and also continue doing so anytime there's an update that adds new features that are enabled by default.
- But most importantly, it's incredibly difficult to configure.

Expanding that last point, I understand there's a GUI and it's reasonably decent, however that's *probably* not how we're going to be adding, updating, or removing most recipes. Instead what's more likely is what we're currently doing right now: suggesting updates to text-based config files. And this is the config file for a dead basic `honey block -> 4 honey bottles` recipe:
```json
{
  "group" : "",
  "hidden" : false,
  "priority" : "NORMAL",
  "exactItemMeta" : true,
  "conditions" : [ {
    "id" : "world_name",
    "option" : "IGNORE",
    "names" : [ ]
  }, {
    "id" : "world_biome",
    "option" : "IGNORE",
    "biomes" : [ ]
  }, {
    "id" : "world_time",
    "option" : "IGNORE",
    "time" : 0
  }, {
    "id" : "weather",
    "option" : "IGNORE",
    "weather" : "NONE"
  }, {
    "id" : "permission",
    "option" : "IGNORE",
    "permission" : "customcrafting.craft.%namespace%.%recipe_name%"
  }, {
    "id" : "elite_crafting_table",
    "option" : "IGNORE",
    "elite_crafting_tables" : [ ]
  }, {
    "id" : "advanced_workbench",
    "option" : "IGNORE"
  }, {
    "id" : "player_experience",
    "option" : "IGNORE",
    "experience" : 0
  } ],
  "shapeless" : true,
  "result" : [ {
    "custom_amount" : 4,
    "item" : {
      "==" : "org.bukkit.inventory.ItemStack",
      "v" : 2586,
      "type" : "HONEY_BOTTLE",
      "amount" : 4
    }
  } ],
  "ingredients" : {
    "E" : [ {
      "custom_amount" : 1,
      "item" : {
        "==" : "org.bukkit.inventory.ItemStack",
        "v" : 2586,
        "type" : "HONEY_BLOCK"
      }
    } ]
  },
  "shapeless" : true
}
```
It's not *entirely* illegible, don't get me wrong, but it's a bit much for what we need, and imagine what it'd be like for more complicated patterns. That being said, I'm not saying that just because CustomCrafting is not a good fit for us that we should just settle on my hack :P something I've just remembered is [RecipeManager2](https://github.com/Protonull/RecipeManager2), a plugin I've been """"maintaining"""" as it's a dependency of CivSpy. We might want to look into that plugin, particularly since it's open source and apparently been used before in civ.

**Comment by Diet-Cola** [comment]
currently on Devoted we're running https://github.com/DutchJelly/CraftEnhance, pretty decent and does everything we need

**Comment by Protonull** [comment]
Would you be able to post Devoted's CraftEnhance config here so we can see what it looks like?

**Comment by Diet-Cola** [comment]
They have an ingame GUI for disabling recipes and creating them but they have multiple configs in the file, for example:
Disabled recipes:
```
disabled:
- minecraft:diamond_boots
- minecraft:diamond_helmet
- minecraft:diamond_chestplate
- minecraft:diamond_leggings
```
Custom recipes:
```
recipe1:
  ==: com.dutchjelly.craftenhance.crafthandling.recipes.WBRecipe
  result: MUSHROOM_STEW
  hidden: false
  recipe:
  - null
  - null
  - null
  - null
  - null
  - CRIMSON_FUNGUS
  - null
  - WARPED_FUNGUS
  - BOWL
  permission: null
  slot: -1
  page: -1
  matchmeta: true
  shapeless: true
```
^ this is also repeated for every recipe in the same file, just posted 1 as an example
and then it has a custom item reference config
```
Souls:
  ==: org.bukkit.inventory.ItemStack
  v: 2584
  type: ENDER_EYE
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '{"extra":[{"text":"Souls"}],"text":""}'
    lore:
    - '{"extra":[{"text":"Activity reward used in factories"}],"text":""}'
Souls1:
  ==: org.bukkit.inventory.ItemStack
  v: 2584
  type: ENDER_EYE
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '{"text":"","extra":[{"text":"Souls"}]}'
    lore:
    - '{"text":"","extra":[{"text":"Activity reward used in factories"}]}'
```
We use this to convert our broken souls to the working format when we had that bug

**Comment by Diet-Cola** [comment]
Example of how we use the bottom config:
```
recipe3:
  ==: com.dutchjelly.craftenhance.crafthandling.recipes.WBRecipe
  result: Souls
  hidden: false
  recipe:
  - null
  - null
  - null
  - null
  - Souls1
  - null
  - null
  - null
  - null
  permission: null
  slot: -1
  page: -1
  matchmeta: true
  shapeless: true
```

**Comment by Protonull** [comment]
wait, is this the custom crafting thing that's done in a chest gui and not a crafting matrix?

**Comment by Diet-Cola** [comment]
It uses a chest gui yes but it has a fake crafting grid 
image

**Comment by Diet-Cola** [comment]
define the recipe on the left, then the output in middle, right hand side are all options such as shapeless, permission required etc

**Comment by Protonull** [comment]
That's unfortunate imho, custom crafting recipes shouldn't have to require a custom crafting GUI

**Comment by Diet-Cola** [comment]
Misunderstood, you don't need a custom crafting table/chest, that gui I posted is purely admin side to help create recipes live

**Comment by Protonull** [comment]
Oke, just tinkered with it and it's a decent plugin. I don't mind closing this PR and reverting the addition to SAH to instead use CraftEnhance. @wingzero54 would you be satisfied with that?

**Comment by Diet-Cola** [comment]
I think we had the same problem but I think we just re-registered the recipes w/ the crafting grid

**Comment by Protonull** [comment]
Yeah, CraftEnhance's GUI seems a little barebones, which is fine imho, and since it's open source we can just fork it and #CodeItOurselves :P it doesn't necessarily matter because all the recipes are stored within fairly easily readable text-based config files, so we can just remove the custom recipes from the files manually. As for conflicting recipes, that definitely is a concern, but seems like something we ought to mitigate through vigilance.

**Comment by Protonull** [comment]
So it's been a couple of days now, Wing mentioned in DMs that he's weary about adding new plugins to Civclassics given that that's usually Max's decision, but given that Max has seemingly taken a step back for now, he's open to the idea of putting CraftEnhance on a test server and thoroughly testing everything, particularly in regards to permissions.

And so the choice is between merging this PR and pursing CraftEnhance. UnblockingHack while being extremely basic has already been accepted and merged into SimpleAdminHacks and is on the live server right now, so adding these recipes is a matter of simply merging the PR. We could pursue CraftEnhance in lieu of UnblockingHack, but that's going to take some time and effort with all the testing we'll need to do. In any case, @Diet-Cola would you be able to help with testing, assuming we pursue CraftEnhance, given that you already use it on Devoted Hell?

**Comment by Protonull** [comment]
Have replaced the config for UnblockingHack with CraftEnhance.

**Comment by Protonull** [comment]
Just as a reminder, this is what the UnblockingHack config looked like before being converted into the CraftEnhance config:
```yaml
UnblockingHack:
  enabled: true
  # Block materials that turn into 9 item materials
  # Example => NETHER_WART_BLOCK: NETHER_WART
  9block:
    BROWN_MUSHROOM_BLOCK: BROWN_MUSHROOM
    NETHER_WART_BLOCK: NETHER_WART
    RED_MUSHROOM_BLOCK: RED_MUSHROOM
  # Block materials that turn into 4 item materials
  # Example => CLAY: CLAY_BALL
  4block:
    BRICKS: BRICK
    CLAY: CLAY_BALL
    GLOWSTONE: GLOWSTONE_DUST
    HONEY_BLOCK: HONEY_BOTTLE
    NETHER_BRICKS: NETHER_BRICK
    POLISHED_ANDESITE: ANDESITE
    POLISHED_BASALT: BASALT
    POLISHED_DIORITE: DIORITE
    POLISHED_GRANITE: GRANITE
    PRISMARINE: PRISMARINE_SHARD
    PURPUR_BLOCK: POPPED_CHORUS_FRUIT
    QUARTZ_BLOCK: QUARTZ
    SNOW_BLOCK: SNOWBALL
  # Item materials, 9 of which combine into a block material
  # Example => NETHER_WART: NETHER_WART_BLOCK
  9items:
    BROWN_MUSHROOM: BROWN_MUSHROOM_BLOCK
    RED_MUSHROOM: RED_MUSHROOM_BLOCK
  # Item materials, 4 of which combine into a block material
  # Example => CLAY_BALL: CLAY
  4items:
  STICK: OAK_PLANKS
```

**Pull request merged**
