### PR TITLE
Add high piston limit to allow flying machines but also discourage ri…

### PR DESCRIPTION
**Pull request by Convoy20**
…diculous piston usage

Add high piston limit to allow flying machines but also discourage ridiculous piston usage

### CODE REVIEW

**Comment by wingzero54** [comment]
The flying machines I'm familiar with are 15 blocks in total (including pistons and every block touching/being moved by the pistons). Can you make any larger than that?

**Comment by caucow** [comment]
> The flying machines I'm familiar with are 15 blocks in total (including pistons and every block touching/being moved by the pistons). Can you make any larger than that?

push limit is 12 blocks, so you can make a 24 block total machine. depending on design that can get to iirc 18 or 20 blocks long depending on how stable you want it to be during lag

**Comment by Convoy20** [comment]
> The flying machines I'm familiar with are 15 blocks in total (including pistons and every block touching/being moved by the pistons). Can you make any larger than that?

I put it higher incase someone had multiple of those 15 block flying machines going at the same time. At ~30 if two of those machines entered the same chunk it could cause problems. 50 seemed high enough to avoid any issues which discouraging piston farms.

**Comment by wingzero54** [comment]
Sure may as well I guess, as a failsafe

**Pull request merged**
