### PR TITLE
Change Exilepearl to tick less regularly. Sue me

### PR DESCRIPTION
**Pull request by Convoy20**
Exilepearl ticks every 8hrs

### CODE REVIEW

**Comment by wingzero54** [comment]
@Diet-Cola really, is there any downside to just ticking pearls less like this? Pearl health will change a little more drastically, but it will still be updated 4 times a day

**Comment by Diet-Cola** [comment]
I remember looking at EP stuff and it checks if a pearls health is equal to 0, not less than or equal so we have to make sure it will properly handle a potential sub-zero health from stuff like this

**Comment by wingzero54** [comment]
Optimal solution would still be to spread the pearl ticking task out better

**Comment by Convoy20** [comment]
> Optimal solution would still be to spread the pearl ticking task out better

Why not merge this for now until that task gets assigned and completed?

**Comment by wingzero54** [comment]
Not the way I wanna go about it, there's a PR for adjusting pearls so the tick won't be intensive

**Pull request closed without merging**
